secret:
    enabled: ENC[AES256_GCM,data:dNDQzw==,iv:BkKXRyeKwVsaTWk/r7UGyShluSsHU+S0EOZFNu5MPRY=,tag:9kQCmaXsmPrYUqaljaoVxA==,type:bool]
    additionalLabels: null
    annotations: null
    files:
        - nameSuffix: ENC[AES256_GCM,data:NOFUk1oH,iv:+e9lnyVuIORT3ONbWABB37X4F6OA05yLu8rid7rNsks=,tag:/X0WVvZpoOhANJ8CA7+XEA==,type:str]
          data:
            config: ENC[AES256_GCM,data:TzWIPGUPoRDQOdw+6qbEM8faoJEWJQJ4MG4STh4kFRXj1bLE63LVBdnfTmH24Pd6QMgU0vbpgZfcltaFSi3zaCWoPQSnpEz47QVH9PU25I2iu14ERrcE/c9bQzjt31WWSWOPPHe3kjvVh1EFJUl1U+V4bFGpCzQfyzpRmcor0oug6/1dQ9PkEuxoX7rfDYDqy7adXUxqJJLOUTw2LQJQO5Pe7FN16889wjGczgfz16171+AnxwDs3mMsXkw/1DiIIQyNmc6W/Boy+jIgrTYOZuWKNSzAb3aXK3pso03fa15OJhtix3M71Y795va+ezvprXycwnDe+FSu9n9pSgzA88t86ZAMN+hBLOCv4N6mt/wIkXQjGZMcoHQI/FzFtQcGgKt7KB+ZqEmC5EwLAJ1/0orXb+sXjjxAY5jceKqtMHz4k2uyAe225k0M2OBDlX+DMoQFsutKNSUy9SG9ywRK7ulufkF7Z/2jl5QnsscX66ni13f61ywgpgWY6j7Es9+co6DBx7D0LN0feuNgVNAatfH7T3m7jIyEbA82oNE5LDVs6YnfakFs6jov59Z+GKKVohBRNOzNWfarZJmCIBu13pww/ey7iYcBsEnlS4/RqaZFKpExW6cXeLdKhNEGlZf2BvbCvqbSewPMhAac05X0dmXbvFV+qujI3dklUq8TPxei43MPzoTW1GK5oJP52rquK8NtEigypmC7v7Klwh9Dg0fhi2qr1KW3zSPNqSaLXShDZfW69t273j172K2mbA+1/CguJFepx6lO5ZRi30QlzTFUv0tkEbV/DEhOvoxrl95a/UA9G7fBQT2mqTsB3NiJUKXGDtV0P8V+uk1z5bIoSZYhaI0qZh4YgMzjDfQSdWjGeWZHaMKX2LpQu7Ptar6mpD9YlE3ATY16MP+XZ8TrX8sI2rYymjGSAAXn894OXmzseNKp/MK5WHjpOo4nV0jwP74XggQWzx+pa0zaO7UndhDqQ8WZHApPS/6wtaEQbLpOz3LfrcCWsJb28oVNMpqRX+WOiS2OMFNpmZzrP8tM+i7VIBPg7/BtkDeu1QxRc0wCYw==,iv:kriIjI5eMmVLVgLN8G9L6zRk+2u/y456Nk9T5PXOt1Q=,tag:EtSpIyXoHwWTYKAU44dFug==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-prod-app-secrets
          created_at: "2025-02-25T13:45:32Z"
          enc: AQICAHjq02t1lRPrkFWL3hb3GH+5y6T3WpMLOHeZkgYkrzuQAQF6Nt9lvGiauhw5MIK+of9yAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMX0k2Fs7+tF+qytfwAgEQgDut5/EBVrpYppkKTN9336WhqvWNvlZMgQoM+O+yKj3O2C+5T/EluyJXqv+ST25CKN1K8nwczDAFXRdxyg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-25T13:45:33Z"
    mac: ENC[AES256_GCM,data:6RkZeOslWtlJSoZ5fa0JNxE0kPtt8pukX0OngHHwUj0bBDKyxNNM3kz2/Gr6DnGTQtr5Ac8EBg5qiqw0vKCAqLO5umj5oSsOotozGfjqWr4Br58T51XezG8IUm74LzlAtW58+coFto/O4bgstQj5eNjGaq/CNtzKzcFhO8cNO1A=,iv:+AoUczF9ys6ag8XOVl6xY20icXYMSmtcJg4D8ruyLMw=,tag:jpvlhCbPsWHNNIx7Y5pD4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
