secret:
    enabled: ENC[AES256_GCM,data:+PAv1w==,iv:eLNdjWhlyv2fCEi+uPFzYOLUy6nzjJmhURdL4gCjVFI=,tag:vRJdhy4ITy+mdPyruqRyIA==,type:bool]
    additionalLabels: null
    #ENC[AES256_GCM,data:ky4ShDjgmH7av9k=,iv:LyoGQ26ateyumm1aPFkgLoTvrJfN4Sr36zU5COkG5cU=,tag:bl6CMgMwqDCgbG3gpojY1g==,type:comment]
    annotations: null
    #ENC[AES256_GCM,data:IkKSorOMZUhmNZ0=,iv:09ezOBLA4p8rj2QnqeyJiyoXdG2d3cO+LSaKzOQuhyA=,tag:27g62Dl6ir7m6kbHMlj6Qg==,type:comment]
    files:
        - nameSuffix: ENC[AES256_GCM,data:z1L2U3wz,iv:nb487ZgFNe/zm1z2qjYRIlPmo0quB4QSPCKnoeNMv+I=,tag:nXnvxEMP+r9470QRMC5ljQ==,type:str]
          data:
            env: ENC[AES256_GCM,data:6VQVPLgz1yBNhuYlRTbmp0FB2wo66LLcpKjGjSuNI/IdnhigS6NuoxymqwSypENZWcw9zLODeKEJfxGr/TixTmeV5VkORY/5iGhnrh6upMeWX8HCZSwsWth3T/7g9kRVvOI+4yul3GOiDFuyfK43j9mIbfQ35axmU3nglGK2fLVwhNawCGuTCyR1kbuc/gj8bY5LCw3U8H1so71F9aXmasjGQbCVNBUcA4HnhkbqTl/agKichVJX7bvau8szVaeARmeu7D5KQLdyJEDzwoMIySq+92N2u0EpUohWVhP3hWABLF1VOeoCtOweLpMLIyK5nf9750hDBDf1bShhyFqF6ZrhHsaiBckUOLsI0jNZ0S4ux3hrw5nHIICziPdPPeWVSj9E4dYYMsCCAKpwOvTqTv+6FnrFqkryE6kEooc8vr6PG8pA7bUufMP+y55GNsK7ZIOE/LFxjNAr,iv:8aBnUVAWrDgMAUUsDF62XICNAevPwUnp7aaR8LlT5iI=,tag:CaSGYBKt4QofUGZAq6G4ZQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-af1-prod-app-secrets
          created_at: "2026-03-02T20:05:39Z"
          enc: AQICAHh9ogVWIDO0uRL7tEmNc+B29gwmecJObjj7g9YLk6lplwE3xsGIn0zVp55UJAgKCe3ZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTQyk2uIOJZbq4UFgAgEQgDsaJZaEu8FDGLA9nbImms4Xpa1Saka83EUGz9TrtM9NqjwIydLjkb6t6pzidIG/xGuqhRnl92nYJ5dTFg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-02T20:05:40Z"
    mac: ENC[AES256_GCM,data:nEGBGdb93TZpVNZazboluIkMQG6D0Rp2KRMGFJm4xKiWw/uj/TPj0lw8eTbkXixYaCt67FnvXUB1UnRPWkbt3mN5l8ult/qahUq/B7t0l+KQO3OlzLUSKE9IVAwRquO9ayNocmep1RS/7zy9R5NSH2fjuuL5q9M7r31lEG59cqM=,iv:kYtU4fHcLbnmFxrDn6dyzWL/D2v+aj9BQGQCgwAJjhc=,tag:1VP0e/8wgJFF/A+9qWD9Og==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
