secret:
    enabled: ENC[AES256_GCM,data:jnrIZQ==,iv:gZhbazFykXN8EWfujhR6dYl6mxHhd3ebWL2+kdkkR98=,tag:BVXa/ROYgr1YBkS04zHvVA==,type:bool]
    additionalLabels: null
    annotations: null
    files:
        - nameSuffix: ENC[AES256_GCM,data:vuw=,iv:xBSm9SeLAtcbNNAmfGy5alKSSFWcb1M7n07Jsr9H9/Q=,tag:88fH6V14BP2oWiQl8dh+7Q==,type:str]
          data:
            DB_HOST: ENC[AES256_GCM,data:BLm4w8o/yMQf7slzHfQR144RBnKR//J0enps/zws+zCmv3WTsl4oHJ94dzdWuG1/NaLAKt/FtoUOQxZ+6Nyh6gt8Gl7SAIPe7A==,iv:HoywGwE9yHZDDpYI1M3paHlAT5D6u7hxeU6VTaKFBIY=,tag:rCJE0Blnu+AHqg/bbldl4A==,type:str]
            DB_NAME: ENC[AES256_GCM,data:/aDiQNxy/Jn1vjbP5+56,iv:HIegcZ1a3VddYqW4dKCYjaeFfOkbBzTAeBo5ssEStGU=,tag:MAW/8hlQxKJKqZDIPj7v5Q==,type:str]
            DB_PASS: ENC[AES256_GCM,data:K4n6e6qHe9Lj0MreGaKasaTAM2k=,iv:3mBZjXKrgGEKWkZAmmGVjQm3ac375GDJe1CU6b4YmWs=,tag:B1XRa/pTCHN8YayiDR1yTg==,type:str]
            DB_USER: ENC[AES256_GCM,data:OAwTxQ==,iv:QPIbNvTTQfcWEs61f/458yWk/ygJEMD5ILTSZpqSqeE=,tag:Mjv2UTp2aFJr0R1vgJ073g==,type:str]
            DCC_KEY: ENC[AES256_GCM,data:Szn1NKeFrKK6xlRJxiP9kA==,iv:h4lAgZnvNbYWOmFKb8uNzk3eGcReOpIqfBpgA+IHnbw=,tag:eXYVowuBQK6HOUXPZGP4aQ==,type:str]
            DCC_SECRET: ENC[AES256_GCM,data:Y3LiD7lSaYH+pHj3N9Gis4Bb+Mi8Zwl2aE4=,iv:VBeQw444gmmaHgROvhSAnCGpzi/itv4ByF3uV1vqFl4=,tag:DuR4wmrmAIY8ngaf9MbzAw==,type:str]
            HMAC_SECRET_KEY: ENC[AES256_GCM,data:5J/pDhJMcklPnwj3o9BVHUeLqyOAKlp9an14AbK/OcQe,iv:ZKUM9Jg9SS7GUREUDD2LhNS2Ru5LIAHOYx2uw5fOQfA=,tag:OOmuXKMNee+G8OrZwOMAoA==,type:str]
            DCC_SERVER: ENC[AES256_GCM,data:7dG3TfOkLUxq88uHp8Bxq4h7M6X59TE=,iv:psIYTBefzVnVIt3jl4N+jgkrt/Ud/ws99XWnWCG2+EA=,tag:qDMOE3IgttCag4gCeuAWZA==,type:str]
            BUMP_UP_RATE: ENC[AES256_GCM,data:6g==,iv:YWE5bEKGcNm6lO5jdY8u4rpSeriZVDlM+IdGnEpQyh8=,tag:+aVG/MnsqvKprWcDPfky9A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:af-south-1:617217039186:alias/gti-paydart-prod-app-secrets
          created_at: "2026-01-28T10:59:19Z"
          enc: AQICAHjq02t1lRPrkFWL3hb3GH+5y6T3WpMLOHeZkgYkrzuQAQHBiSMu5z4V9OvvtTLOAscyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf4izta7fcr4caSbVAgEQgDtLANuLB388bxfiNq9q0/poemiUSaXWHbdEraCtcEcRK9dOzKXWliHkLWZRlHtni0I9BUjVtwHQ19DPWA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-28T10:59:20Z"
    mac: ENC[AES256_GCM,data:m+23afZyOM9+t/qnXgWhuLOCyN3BfUuVf3cd0aK2e4Azah6gJX+zpTu1tcLNDhJnmoQLNUVk1z6G1Odf31/uhdr3wn/dJeeMxJlgzjd8Ni1175WpEEJOEuk3rkR+rubjMHIlFN8/Sz41nREGZOHRxj/Gy8nQRZKwiLdMQhUf1TE=,iv:hx2ZQFfJb54HRULj+t0v1h9jyxGAm8/nwFMkR5Z0Hi4=,tag:INN3EcSGcB3+KEhV5sVr/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
